(markovbot) arch% ./markov.py 
Connecting to database
->host='localhost' dbname='testdb' user='postgres' password='postgres'
Connected!

Traceback (most recent call last):
  File "./markov.py", line 108, in <module>
    if str(r) == 'null':
UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f62f' 
in position 0: ordinal not in range(128)
